QAT.Environment.LoginUrl=https://opensource-demo.orangehrmlive.com
QAT.Environment.DashboardUrl=https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index
QAT.Environment.WebserviceUrl=https://opensource-demo.orangehrmlive.com
